# Generated by Django 5.0 on 2023-12-24 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notes',
            options={'verbose_name': 'Привычка', 'verbose_name_plural': 'Привычки'},
        ),
    ]
